[main]
lines=3
width=9

line-height=35
horizontal-pad=5
vertical-pad=5
inner-pad=5

letter-spacing=1px
use-bold=1

# Positioning (key part)
anchor=top-right
x-margin=6
y-margin=6

[colors]
background=0a0a0af5
text=ffffffff

selection=cdd6f4ff
selection-text=000000ff

border=cdd6f4ff

[border]
width=2
