[main]
lines=4
width=15

line-height=25
horizontal-pad=18
vertical-pad=10
inner-pad=5

# Positioning (key part)
anchor=top-right
y-margin=10
x-margin=10

[colors]
background=0a0a0af5
text=ffffffff

selection=cdd6f4ff
selection-text=000000ff

border=cdd6f4ff

[border]
width=2
